name: ogre-meshviewer
version: "22.11"
confinement: strict
summary: OGRE Mesh Viewer
description: Viewer for .mesh model files as consumed by OGRE
base: core20

apps:
    ogre-meshviewer:
        command: bin/desktop-launch python3 $SNAP/bin/ogre_mesh_viewer.py
        plugs: [home, opengl, x11, removable-media]
        environment:
            PYTHONPATH: $SNAP/usr/lib/python3.8/dist-packages/
parts:
    desktop-glib-only:
        source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
        source-subdir: glib-only
        plugin: make
    ogre:
        plugin: cmake
        cmake-parameters:
            - -DCMAKE_BUILD_TYPE=Release
            - -DOGRE_BUILD_DEPENDENCIES=FALSE
            - -DOGRE_BUILD_RENDERSYSTEM_GL3PLUS=TRUE
            - -DOGRE_BUILD_RENDERSYSTEM_GL=TRUE
            - -DOGRE_BUILD_RENDERSYSTEM_GLES2=TRUE
            - -DOGRE_BUILD_COMPONENT_PYTHON=TRUE
            - -DOGRE_BUILD_PLUGIN_DOT_SCENE=TRUE
            - -DOGRE_BUILD_COMPONENT_TERRAIN=TRUE
            - -DOGRE_BUILD_COMPONENT_PAGING=TRUE
            - -DPYTHON_EXECUTABLE=/usr/bin/python3
            # stuff we dont need for the viewer
            - -DOGRE_BUILD_TOOLS=FALSE
            - -DOGRE_BUILD_SAMPLES=FALSE
            - -DOGRE_BUILD_PLUGIN_STBI=FALSE # we want to use freeimage instead
            - -DOGRE_BUILD_PLUGIN_EXRCODEC=FALSE
            - -DOGRE_BUILD_PLUGIN_BSP=FALSE
            - -DOGRE_BUILD_PLUGIN_PCZ=FALSE
            - -DOGRE_BUILD_PLUGIN_OCTREE=FALSE
            - -DOGRE_BUILD_COMPONENT_JAVA=FALSE
            - -DOGRE_BUILD_COMPONENT_CSHARP=FALSE
            - -DOGRE_BUILD_COMPONENT_VOLUME=FALSE
            - -DOGRE_BUILD_COMPONENT_PROPERTY=FALSE
            - -DOGRE_BUILD_COMPONENT_HLMS=FALSE
            - -DOGRE_BUILD_COMPONENT_MESHLODGENERATOR=FALSE
            - -DCMAKE_INSTALL_PREFIX=/usr/
            - -DCMAKE_CXX_COMPILER=/usr/bin/clang++-12
        source: https://github.com/OGRECave/ogre.git
        source-tag: v13.5.2
        source-depth: 1
        build-packages:
            - libassimp-dev
            - libxaw7-dev
            - libxrandr-dev
            - libfreetype6-dev
            - libfreeimage-dev
            - libxt-dev
            - libgles2-mesa-dev
            - libsdl2-dev
            - libpython3-dev
            - libpugixml-dev
            - swig3.0
            - clang-12
            - try: [nvidia-cg-dev]
        stage-packages:
            - libassimp5
            - libfreetype6
            - libfreeimage3
            - libsdl2-2.0-0
            - python3
            - libpython3.8
            - libpugixml1v5
            - libxaw7
            - libxt6
            - libgl1
            - libgles2
            - libegl1
            - try: [libcggl]
        stage:
            - -usr/share/OGRE/Media/volumeTerrain
            - -usr/share/OGRE/Media/materials
            - -usr/share/OGRE/Media/models
            - -usr/share/OGRE/Media/thumbnails
            - -usr/share/OGRE/Media/packs/chiropteraDM.pk3
            - -usr/share/OGRE/Media/packs/fresneldemo.zip
            - -usr/share/OGRE/Media/packs/DamagedHelmet.zip
            - -usr/share/OGRE/resources.cfg
    viewer:
        plugin: dump
        source: https://github.com/OGRECave/ogre-meshviewer.git
        organize:
            ogre_mesh_viewer.py: bin/
        stage:
            - bin/
        after: [ogre, desktop-glib-only]
