name: ogre-meshviewer
version: "23.07"
confinement: strict
summary: OGRE Mesh Viewer
description: Viewer for .mesh model files as consumed by OGRE
base: core22

apps:
    ogre-meshviewer:
        command: bin/desktop-launch python3 $SNAP/bin/ogre_mesh_viewer.py
        plugs: [home, opengl, x11, removable-media]
        environment:
            PYTHONPATH: $SNAP/usr/lib/python3.10/:$SNAP/usr/lib/python3.10/dist-packages/:$SNAP/usr/lib/python3.10/lib-dynload
            TCL_LIBRARY: $SNAP/usr/share/tcltk/tcl8.6
parts:
    desktop-glib-only:
        source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
        source-subdir: glib-only
        plugin: make
    ogre:
        plugin: cmake
        cmake-parameters:
            - -DCMAKE_BUILD_TYPE=Release
            - -DOGRE_BUILD_DEPENDENCIES=FALSE
            - -DOGRE_BUILD_RENDERSYSTEM_GL3PLUS=TRUE
            - -DOGRE_BUILD_RENDERSYSTEM_GL=TRUE
            - -DOGRE_BUILD_RENDERSYSTEM_GLES2=TRUE
            - -DOGRE_BUILD_PLUGIN_RSIMAGE=TRUE 
            - -DOGRE_BUILD_COMPONENT_PYTHON=TRUE
            - -DOGRE_BUILD_PLUGIN_DOT_SCENE=TRUE
            - -DOGRE_BUILD_COMPONENT_TERRAIN=TRUE
            - -DOGRE_BUILD_COMPONENT_PAGING=TRUE
            - -DPYTHON_EXECUTABLE=/usr/bin/python3
            # stuff we dont need for the viewer
            - -DOGRE_BUILD_TOOLS=FALSE
            - -DOGRE_BUILD_SAMPLES=FALSE
            - -DOGRE_BUILD_PLUGIN_STBI=FALSE # we want to use rsimage instead
            - -DOGRE_BUILD_PLUGIN_FREEIMAGE=FALSE
            - -DOGRE_BUILD_PLUGIN_EXRCODEC=FALSE
            - -DOGRE_BUILD_PLUGIN_BSP=FALSE
            - -DOGRE_BUILD_PLUGIN_PCZ=FALSE
            - -DOGRE_BUILD_PLUGIN_OCTREE=FALSE
            - -DOGRE_BUILD_COMPONENT_JAVA=FALSE
            - -DOGRE_BUILD_COMPONENT_CSHARP=FALSE
            - -DOGRE_BUILD_COMPONENT_VOLUME=FALSE
            - -DOGRE_BUILD_COMPONENT_PROPERTY=FALSE
            - -DOGRE_BUILD_COMPONENT_MESHLODGENERATOR=FALSE
            - -DCMAKE_INSTALL_PREFIX=/usr/
            - -DCMAKE_CXX_COMPILER=/usr/bin/clang++-15
        source: https://github.com/OGRECave/ogre.git
        source-tag: master
        source-depth: 1
        build-packages:
            - libassimp-dev
            - libxrandr-dev
            - libfreetype6-dev
            - libgles2-mesa-dev
            - libsdl2-dev
            - libpython3-dev
            - libpugixml-dev
            - swig4.0
            - clang-15
            - cargo
            - on amd64: [nvidia-cg-dev]
        stage-packages:
            - libassimp5
            - libfreetype6
            - libsdl2-2.0-0
            - python3
            - python3-tk
            - libpython3.10
            - libpugixml1v5
            - libgl1
            - libsm6
            - libgles2
            - libegl1
            - on amd64: [libcggl]
    viewer:
        plugin: dump
        source: https://github.com/OGRECave/ogre-meshviewer.git
        organize:
            ogre_mesh_viewer.py: bin/
            fonts: bin/fonts
        stage:
            - bin/
        after: [ogre, desktop-glib-only]
