name: ogre-meshviewer
version: "19.05"
confinement: strict
summary: OGRE Mesh Viewer
description: Viewer for .mesh model files as consumed by OGRE
base: core18

apps:
    ogre-meshviewer:
        command: desktop-launch python3 $SNAP/bin/ogre_mesh_viewer.py
        plugs: [home, opengl, x11]
parts:
    desktop-glib-only:
        source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
        source-subdir: glib-only
        plugin: make
    ogre:
        plugin: cmake
        configflags:
            - -DCMAKE_BUILD_TYPE=Release
            - -DOGRE_CONFIG_THREAD_PROVIDER=std
            - -DOGRE_CONFIG_THREADS=3
            - -DOGRE_STATIC=FALSE
            - -DOGRE_BUILD_DEPENDENCIES=FALSE
            - -DOGRE_BUILD_RENDERSYSTEM_GL3PLUS=TRUE
            - -DOGRE_BUILD_RENDERSYSTEM_GL=TRUE
            - -DOGRE_BUILD_RENDERSYSTEM_GLES2=TRUE
            - -DOGRE_BUILD_COMPONENT_PYTHON=TRUE
            - -DPYTHON_EXECUTABLE=/usr/bin/python3
            # stuff we dont need for the viewer
            - -DOGRE_BUILD_TOOLS=FALSE
            - -DOGRE_BUILD_SAMPLES=FALSE
            - -DOGRE_BUILD_PLUGIN_STBI=FALSE # we want to use freeimage instead
            - -DOGRE_BUILD_PLUGIN_EXRCODEC=FALSE
            - -DOGRE_BUILD_PLUGIN_BSP=FALSE
            - -DOGRE_BUILD_PLUGIN_PCZ=FALSE
            - -DOGRE_BUILD_PLUGIN_OCTREE=FALSE
            - -DOGRE_BUILD_PLUGIN_DOT_SCENE=FALSE
            - -DOGRE_BUILD_COMPONENT_JAVA=FALSE
            - -DOGRE_BUILD_COMPONENT_CSHARP=FALSE
            - -DOGRE_BUILD_COMPONENT_VOLUME=FALSE
            - -DOGRE_BUILD_COMPONENT_TERRAIN=FALSE
            - -DOGRE_BUILD_COMPONENT_PAGING=FALSE
            - -DOGRE_BUILD_COMPONENT_PROPERTY=FALSE
            - -DOGRE_BUILD_COMPONENT_HLMS=FALSE
            - -DOGRE_BUILD_COMPONENT_MESHLODGENERATOR=FALSE
            - -DCMAKE_INSTALL_PREFIX=/usr/
            - -DCMAKE_CXX_COMPILER=/usr/bin/clang++-8
        source: https://github.com/OGRECave/ogre.git
        source-tag: master
        build-packages:
            - libxaw7-dev
            - libzzip-dev
            - libxrandr-dev
            - libfreetype6-dev
            - libfreeimage-dev
            - libxt-dev
            - libgles2-mesa-dev
            - libsdl2-dev
            - libpython3-dev
            - swig3.0
            - clang-8
        stage-packages:
            - libfreetype6
            - libfreeimage3
            - libzzip-0-13
            - libsdl2-2.0-0
            - python3
            - libpython3.6
            - libxaw7
            - libxt6
            - try: [nvidia-cg-dev] # should be in build-packages, but we have no try: there
            - try: [libcggl]
        stage:
            - -usr/share/OGRE/Media/volumeTerrain
            - -usr/share/OGRE/Media/materials
            - -usr/share/OGRE/Media/models
            - -usr/share/OGRE/Media/thumbnails
            - -usr/share/OGRE/Media/packs/chiropteraDM.pk3
            - -usr/share/OGRE/Media/packs/fresneldemo.zip
            - -usr/share/OGRE/Media/packs/DamagedHelmet.zip
            - -usr/share/OGRE/resources.cfg
    ogre-imgui:
        plugin: cmake
        configflags:
            - -DCMAKE_BUILD_TYPE=Release
            - -DCMAKE_INSTALL_PREFIX=/usr/
            - -DCMAKE_CXX_FLAGS=-std=c++11
            - -DBUILD_EXAMPLE=FALSE
            - -DPYTHON_EXECUTABLE=/usr/bin/python3
        source: https://github.com/OGRECave/ogre-imgui.git
        source-tag: master
        after: [ogre]
    viewer:
        plugin: dump
        source: https://github.com/OGRECave/ogre-meshviewer.git
        organize:
            ogre_mesh_viewer.py: bin/
        stage:
            - bin/
        after: [ogre, ogre-imgui, desktop-glib-only]