name: CI Build
on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-tk xvfb libxrandr2 libegl1
        pip3 install ogre-python
    - uses: actions/checkout@v4
    - name: Test
      run: |
        cd test
        xvfb-run timeout --preserve-status 5s python3 ../ogre_mesh_viewer.py cube.obj